services:

  web:
    container_name: app-php
    build: ./docker-config/php
    ports:
      - '5173:5173'
    volumes:
      - .:/var/www/
    depends_on:
      - db

  nginx:
    container_name: app-nginx
    build: ./docker-config/nginx
    ports:
      - '81:80'
    volumes:
      - .:/var/www/
      - ./docker-config/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web

  db:
    container_name: app-db
    image: mariadb
    ports:
      - '3306:3306'
    volumes:
      - ./docker-config/mariadb/data:/var/lib/mysql
      - ./docker-config/mariadb/data/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker-config/mariadb/data/sql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: ${TZ}